#!/bin/sh
if [ -z "$1" ]
then
  echo "Which folder do you want to deploy to GitHub Pages?"
  exit 1
fi

echo "Started deploying"

cd $1

bower install
bundle exec jekyll build

mv _site/* ./../dist
rm -R _site/

# Push to gh-pages.
git add dist
git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"

bower install

cd -

git push origin `git subtree push --prefix dist origin gh-pages`:gh-pages --force

echo "Deployed Successfully!"

exit 0
