assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: # Add Google Analytics tracking code

gems:
  - jekyll-assets
  - jekyll-sitemap

name: Email Mining

permalink: pretty

url: # Add your site url

theme: jekyll-theme-cayman

title: Email Mining
description: The goal of this project is to convert the original Enron Email Dataset into mordern format for investigation.

github:
  repository_name: email-mining
  project_tagline: The goal of this project is to convert the original Enron Email Dataset into mordern format for investigation.
  repository_url: https://github.com/emorynlp/email-mining
  owner_url: https://github.com/emorynlp
  owner_name: Emory NLP
  is_project_page: true
